apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unityexpress-ingress
  namespace: unityexpress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: ui.localdev
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: unityexpress-web
            port:
              number: 80

  - host: api.localdev
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: unityexpress-api
            port:
              number: 80
