apiVersion: v1
kind: Service
metadata:
  name: unityexpress-api
spec:
  type: NodePort
  selector:
    app: unityexpress-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30030
