apiVersion: v1
kind: Service
metadata:
  name: {{ include "unityexpress.api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unityexpress.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: unityexpress-api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      nodePort: {{ .Values.api.service.nodePort }}