apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: unityexpress
type: Opaque
data:
  # base64("unityexpress-kafka.unityexpress.svc.cluster.local:9092")
  bootstrapServers: dW5pdHlleHByZXNzLWthZmthLnVuaXR5ZXhwcmVzcy5zdmMuY2x1c3Rlci5sb2NhbDo5MDky

  # base64("false")
  sasl: ZmFsc2U=
  tls: ZmFsc2U=
