apiVersion: v1
kind: Service
metadata:
  name: {{ include "unityexpress.kafka.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unityexpress.kafka.labels" . | nindent 4 }}
spec:
  ports:
    - name: kafka
      port: {{ .Values.kafka.port }}
      targetPort: {{ .Values.kafka.port }}
  selector:
    app: unityexpress-kafka
---
apiVersion: v1
kind: Service
metadata:
  name: unityexpress-zookeeper
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unityexpress.labels" . | nindent 4 }}
    app: unityexpress-zookeeper
spec:
  ports:
    - name: zk
      port: {{ .Values.kafka.zookeeper.port }}
      targetPort: {{ .Values.kafka.zookeeper.port }}
  selector:
    app: unityexpress-kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unityexpress.kafka.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unityexpress.kafka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: unityexpress-kafka
  template:
    metadata:
      labels:
        {{- include "unityexpress.kafka.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.kafka.zookeeper.image }}
          imagePullPolicy: {{ .Values.kafka.imagePullPolicy }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: {{ .Values.kafka.zookeeper.env.clientPort | quote }}
            - name: ZOOKEEPER_TICK_TIME
              value: {{ .Values.kafka.zookeeper.env.tickTime | quote }}
            - name: ZOOKEEPER_INIT_LIMIT
              value: {{ .Values.kafka.zookeeper.env.initLimit | quote }}
            - name: ZOOKEEPER_SYNC_LIMIT
              value: {{ .Values.kafka.zookeeper.env.syncLimit | quote }}
          ports:
            - name: zk
              containerPort: {{ .Values.kafka.zookeeper.port }}
              protocol: TCP
        - name: kafka
          image: {{ .Values.kafka.image }}
          imagePullPolicy: {{ .Values.kafka.imagePullPolicy }}
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "unityexpress-zookeeper:{{ .Values.kafka.zookeeper.port }}"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:{{ .Values.kafka.port }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://{{ include "unityexpress.kafka.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.kafka.port }}"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: {{ .Values.kafka.env.offsetsTopicReplicationFactor | quote }}
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: {{ .Values.kafka.env.transactionStateLogReplicationFactor | quote }}
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: {{ .Values.kafka.env.transactionStateLogMinIsr | quote }}
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: {{ .Values.kafka.env.autoCreateTopicsEnable | quote }}
          ports:
            - name: kafka
              containerPort: {{ .Values.kafka.port }}
              protocol: TCP
          {{- if .Values.kafka.resources }}
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
          {{- end }}