apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: unityexpress
type: Opaque
data:
  # List of brokers for KEDA (base64 encoded)
  brokers: dW5pdHlleHByZXNzLWthZmthOjkwOTI=

  # SASL and TLS are disabled for this setup
  sasl: ZmFsc2U=
  tls: ZmFsc2U=
