apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unityexpress.labels" . | nindent 4 }}
type: Opaque
stringData:
  bootstrapServers: {{ include "unityexpress.kafkaBrokers" . | quote }}
  sasl: {{ .Values.kafka.secret.saslEnabled | quote }}
  tls: {{ .Values.kafka.secret.tlsEnabled | quote }}