apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: unityexpress
type: Opaque
stringData:
  # This key name must match the deployment: key: bootstrapServers
  bootstrapServers: "unityexpress-kafka:9092"

  # Keep SASL/TLS disabled for local dev
  sasl: "false"
  tls: "false"
