apiVersion: v1
kind: Service
metadata:
  name: unityexpress-mongo
  labels:
    {{- include "unityexpress.labels" . | nindent 4 }}
    app: unityexpress-mongo
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.mongo.port }}
      name: mongo
  selector:
    app: unityexpress-mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unityexpress-mongo
  labels:
    {{- include "unityexpress.labels" . | nindent 4 }}
    app: unityexpress-mongo
spec:
  serviceName: "unityexpress-mongo"
  replicas: 1
  selector:
    matchLabels:
      app: unityexpress-mongo
  template:
    metadata:
      labels:
        {{- include "unityexpress.labels" . | nindent 8 }}
        app: unityexpress-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: {{ .Values.mongo.port }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mongo.storage }}
