apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unityexpress.web.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unityexpress.web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: unityexpress-web
  template:
    metadata:
      labels:
        {{- include "unityexpress.web.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image }}
          imagePullPolicy: {{ .Values.web.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          {{- if .Values.web.resources }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.web.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.web.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.web.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.readinessProbe.periodSeconds }}
          {{- end }}