apiVersion: v1
kind: Service
metadata:
  name: {{ include "unityexpress.web.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unityexpress.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: unityexpress-web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}